CREATE TABLE login
(
USERNAME VARCHAR(30) NOT NULL CONSTRAINT LOGIN_USERRNAME_PK PRIMARY KEY,
PASSWORD VARCHAR(30) NOT NULL,
HINTQUESTION VARCHAR(50),
HINTANSWER VARCHAR(30),
UID INTEGER NOT NULL UNIQUE,
Role VARCHAR(20) NOT NULL
)!
CREATE TABLE PatientPersonal
(
PATIENTID INTEGER NOT NULL CONSTRAINT PatientPersonal_PATIENTID_PK PRIMARY KEY,
PNAME VARCHAR(30) NOT NULL,
FRHNAME VARCHAR(30),
AGE SMALLINT NOT NULL,
GENDER CHAR(2) NOT NULL,
MARITUALSTATUS VARCHAR(10) NOT NULL,
MbileNO BIGINT,
EmailID VARCHAR(30),
Address VARCHAR(120)
)!
CREATE TABLE Doctor
(
DoctorId SMALLINT NOT NULL
CONSTRAINT Doctor_DoctorID_PK PRIMARY KEY,
DOCTORNAME VARCHAR(30) NOT NULL,
DeptNO SMALLINT ,
Designation VARCHAR(30),
ConsultationFee SMALLINT NOT NULL,
FeeValidation SMALLINT,
ConatactNO BIGINT,
MaxPatinetPerDay SMALLINT,
AssignePatients SMALLINT
)!
 CREATE TABLE Department
 (
 DeptNO SMALLINT NOT NULL
 CONSTRAINT Department_Deptno_PK PRIMARY KEY,
 DeptName VARCHAR(30) NOT NULL,
 Location SMALLINT,
 HOD SMALLINT 
 )!
ALTER TABLE Doctor
ADD FOREIGN KEY (Deptno) References Department(Deptno)!
CREATE TABLE PatientTreatmentDetails
(
PatientID INTEGER NOT NULL
CONSTRAINT PatientTreatmentDetails_PatinetId_PK PRIMARY KEY,
DoctorId SMALLINT REFERENCES Doctor(DoctorID),
RoomNO SMALLINT,
PatientType VARCHAR(5)
CONSTRAINT Ptype_check_cnst CHECK(PatientType IN ('IN','OUT')),
Healthhistory VARCHAR(150),
Symptoms VARCHAR(50),
Condition VARCHAR(15),
FinalComments VARCHAR(150),
RefferedTO VARCHAR(50),
DateodAdmission DATE,
DischargeDate DATE
)!
Create Table Room
(
RoomNo SMALLINT
NOT NULL CONSTRAINT Room_RoomNO_PK PRIMARY KEY,
TotalBeds SMALLINT NOT NULL,
AssignedBeds SMALLINT,
CostPerDay SMALLINT NOT NULL,
TYPE VARCHAR(6)
)!
ALTER TABLE PatientTreatmentDetails
ADD FOREIGN KEY (RoomNO) REFERENCES ROOM(ROOMNO)!
CREATE TABLE WorkTimings
(
UID SMALLINT,
Day VARCHAR(6),
StartTime TIME,
EndTime TIME,
FLAG VARCHAR(15)
)!
CREATE TABLE Bill
(
BillNO INTEGER NOT NULL
CONSTRAINT Bill_BillNO_PK PRIMARY KEY,
PatientID INTEGER
REFERENCES PatientPersonal(PatientID) ON DELETE CASCADE,
BillDate DATE,
PaymentMode VARCHAR(10),
AdvPaid INTEGER,
ClaimAmount BIGINT
)!
CREATE TABLE BillDetails
(
PatientID INTEGER 
REFERENCES PatientPersonal(PatientID),
Details VARCHAR(40) NOT NULL,
Amount INTEGER,
BillDate DATE NOT NULL,
Claim VARCHAR(10)
)!
CREATE TABLE Insurance
(
PatientId INTEGER NOT NULL
REFERENCES PatientPersonal(PatientID),
Provider VARCHAR(70) NOT NULL,
InusranceID INTEGER,
ClaimStatus VARCHAR(20),
TotalClaim BIGINT
)!
CREATE TABLE PatientRegistration
(
PName VARCHAR(30) NOT NULL,
FName VARCHAR(30) NOT NULL,
Age SMALLINT NOT NULL,
Gender CHAR(2) NOT NULL,
MobileNo BIGINT,
UserName VARCHAR(30) NOT NULL
CONSTRAINT PRegistration_UName_PK PRIMARY KEY,
Password VARCHAR(30) NOT NULL,
Address VARCHAR(120),
HintQuestion VARCHAR(50),
HintAnswer VARCHAR(30)
)!
CREATE TABLE DOCTORREGISTRATION
(
DName VARCHAR(30) NOT NULL,
ContactNO BIGINT ,
UserName VARCHAR(30) NOT NULL
CONSTRAINT DOCTORREGISTRATION_UNAME_PK PRIMARY KEY,
Password VARCHAR(30) NOT NULL,
Specialization VARCHAR(20),
Experiance SMALLINT NOT NULL,
HintQuestion VARCHAR(50),
HintAnswer VARCHAR(30)
)!
CREATE TABLE Medicine
(
PatientId BIGINT
REFERENCES PatientPersonal(PatientID) ON DELETE CASCADE,
MedicineName VARCHAR(50) NOT NULL,
DoctorId INT NOT NULL
REFERENCES Doctor(DoctorID),
Usage VARCHAR(6),
Dose VARCHAR(8),
Type VARCHAR(12),
Pquantity SMALLINT,
Iquantity SMALLINT,
Date DATE,
Status VARCHAR(12)
)!
CREATE TABLE TESTINFO
(
TestID SMALLINT NOT NULL
CONSTRAINT TESTINFO_TestID_PK PRIMARY KEY,
TestName VARCHAR(35) NOT NULL,
RoomNO SMALLINT,
COST INT
)!
CREATE TABLE PatientTestReport
(
PatientID BIGINT
REFERENCES PatientPersonal(PatientID) ON DELETE CASCADE,
TestId SMALLINT NOT NULL
REFERENCES TestInfo(TestID),
Factor VARCHAR(35) NOT NULL,
FactorValue VARCHAR(30) NOT NULL,
Date DATE,
COMMENTS VARCHAR(30) 
)!
CREATE TABLE TestPrescribed
(
PatientID BIGINT
REFERENCES PatientPersonal(PatientID) ON DELETE CASCADE,
DoctorID SMALLINT
REFERENCES Doctor(DoctorID) ON DELETE SET NULL,
TestID SMALLINT
REFERENCES TestInfo(TestID) ON DELETE SET NULL,
Date TIMESTAMP,
COMMENTS VARCHAR(50)
)!
ALTER TABLE TestPrescribed ADD Status VARCHAR(20)!
CREATE TABLE Prescription
(
PatientID BIGINT
REFERENCES PatientPersonal(PatientId) ON DELETE CASCADE,
DoctorID SMALLINT
REFERENCES Doctor(DoctorId) ON DELETE SET NULL,
Date DATE,
NextVisit DATE,
Comments VARCHAR(200)
)!
ALTER TABLE PatientTreatmentDetails ADD Status VARCHAR(20)!
ALTER TABLE Doctor RENAME COLUMN Dname TO DoctorName!
ALTER TABLE doctor RENAME COLUMN ASSIGNEPATIENTS TO ASSIGNEDPATIENTS!
ALTER TABLE db2admin.TESTPRESCRIBED ALTER COLUMN DATE SET DATA TYPE DATE!